services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # should have multiple *data.sql files
      - ./db/data/:/docker-entrypoint-initdb.d/data/

# docker compose up -d
# docker exec -it mysql-db mysql -u root -p
