name: "[Test] Reddit Scraper"

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

  workflow_dispatch: 

jobs:
    reddit-scraper-tests:
        runs-on: ubuntu-latest
        steps:
          # Step 1: Check out the code from the repository
          - name: Checkout code
            uses: actions/checkout@v3
    
          # Step 2: Set up Python
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.x'
    
           # Step 3: Install dependencies
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
    
          # Step 4: Run unit tests using pytest or any other framework
          - name: Run tests
            env:
              REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
              REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
              REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
            run: |
              coverage run -m pytest tests/test_redditScraper.py