name: "[Test] Database"

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

  workflow_dispatch: 

jobs:
  database-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo apt-get install jq
          sudo service mysql start

      # Step 3: 
      - name: Set up Docker Compose
        run: |
          docker compose version

      # Step 4:
      - name: Start MySQL Service
        env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          docker compose up -d
          docker compose ps

      # Step 5:
      - name: Wait for MySQL to be ready
        run: |
          until docker exec mysql-db mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e 'SHOW DATABASES;' > /dev/null 2>&1; do
            echo "Waiting for MySQL to be ready..."
            docker logs mysql-db
            sleep 5
          done
          echo "MySQL is ready!"

      # Step 6: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 7:
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 8: 
      - name: Run tests
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          python3 tests/databaseTests.py

      # Step 8: 
      - name: Test
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          docker exec mysql-db mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -D ${{ secrets.MYSQL_DATABASE }} -e 'SELECT COUNT(*) FROM NEWS_NVDA_DATA LIMIT 5;'

      # Step 9:
      - name: Tear down Docker Compose
        run: |
          docker compose down 
